# Generated by Django 4.0.3 on 2022-07-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
