# Generated by Django 4.0.3 on 2022-07-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(default='31/07/2022 01:38:42', max_length=100),
        ),
    ]
